[project]
name = "pyjsonparser"
version = "0.1.0"
description = "A modular JSON parser and serializer written in Python with a lexer-parser architecture"
authors = [
    {name = "Ionut-Alexandru Prodan",email = "prodanalexandru1999@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[project.urls]
Homepage = "https://github.com/alexprodan99/pyjsonparser"
Repository = "https://github.com/alexprodan99/pyjsonparser"
Documentation = "https://alexprodan99.github.io/pyjsonparser/"

[tool.poetry]
packages = [{include = "pyjson", from = "src"}]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
